# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_iso.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_iso.proto',
  package='edu.colorado.plv.fixr.protobuf',
  serialized_pb=_b('\n\x0fproto_iso.proto\x12\x1e\x65\x64u.colorado.plv.fixr.protobuf\"\xd7\x04\n\x03Iso\x12\x12\n\ngraph_1_id\x18\x01 \x02(\t\x12\x12\n\ngraph_2_id\x18\x02 \x02(\t\x12=\n\x08map_node\x18\x03 \x03(\x0b\x32+.edu.colorado.plv.fixr.protobuf.Iso.MapNode\x12=\n\x08map_edge\x18\x04 \x03(\x0b\x32+.edu.colorado.plv.fixr.protobuf.Iso.MapEdge\x12\x0e\n\x06weight\x18\x05 \x01(\x01\x12\x11\n\tobj_value\x18\x06 \x01(\x01\x12\x1a\n\x12\x64\x61taNodeMatchCount\x18\x07 \x01(\x04\x12\x1a\n\x12\x64\x61taEdgeMatchCount\x18\x08 \x01(\x04\x12\x1d\n\x15\x63ontrolEdgeMatchCount\x18\t \x01(\x04\x12\x1c\n\x14methodNodeMatchCount\x18\n \x01(\x04\x12\x1a\n\x12\x61verageMatchWeight\x18\x0b \x01(\x01\x12\x1f\n\x17\x61verageDataNodeInDegree\x18\x0c \x01(\x01\x12 \n\x18\x61verageDataNodeOutDegree\x18\r \x01(\x01\x12!\n\x19\x61verageMethodNodeInDegree\x18\x0e \x01(\x01\x12\"\n\x1a\x61verageMethodNodeOutDegree\x18\x0f \x01(\x01\x1a\x35\n\x07MapNode\x12\x0c\n\x04id_1\x18\x01 \x02(\x04\x12\x0c\n\x04id_2\x18\x02 \x02(\x04\x12\x0e\n\x06weight\x18\x03 \x01(\x01\x1a\x35\n\x07MapEdge\x12\x0c\n\x04id_1\x18\x01 \x02(\x04\x12\x0c\n\x04id_2\x18\x02 \x02(\x04\x12\x0e\n\x06weight\x18\x03 \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ISO_MAPNODE = _descriptor.Descriptor(
  name='MapNode',
  full_name='edu.colorado.plv.fixr.protobuf.Iso.MapNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_1', full_name='edu.colorado.plv.fixr.protobuf.Iso.MapNode.id_1', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_2', full_name='edu.colorado.plv.fixr.protobuf.Iso.MapNode.id_2', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='edu.colorado.plv.fixr.protobuf.Iso.MapNode.weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=596,
)

_ISO_MAPEDGE = _descriptor.Descriptor(
  name='MapEdge',
  full_name='edu.colorado.plv.fixr.protobuf.Iso.MapEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_1', full_name='edu.colorado.plv.fixr.protobuf.Iso.MapEdge.id_1', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_2', full_name='edu.colorado.plv.fixr.protobuf.Iso.MapEdge.id_2', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='edu.colorado.plv.fixr.protobuf.Iso.MapEdge.weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=651,
)

_ISO = _descriptor.Descriptor(
  name='Iso',
  full_name='edu.colorado.plv.fixr.protobuf.Iso',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph_1_id', full_name='edu.colorado.plv.fixr.protobuf.Iso.graph_1_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='graph_2_id', full_name='edu.colorado.plv.fixr.protobuf.Iso.graph_2_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map_node', full_name='edu.colorado.plv.fixr.protobuf.Iso.map_node', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map_edge', full_name='edu.colorado.plv.fixr.protobuf.Iso.map_edge', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='edu.colorado.plv.fixr.protobuf.Iso.weight', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obj_value', full_name='edu.colorado.plv.fixr.protobuf.Iso.obj_value', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataNodeMatchCount', full_name='edu.colorado.plv.fixr.protobuf.Iso.dataNodeMatchCount', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataEdgeMatchCount', full_name='edu.colorado.plv.fixr.protobuf.Iso.dataEdgeMatchCount', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='controlEdgeMatchCount', full_name='edu.colorado.plv.fixr.protobuf.Iso.controlEdgeMatchCount', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='methodNodeMatchCount', full_name='edu.colorado.plv.fixr.protobuf.Iso.methodNodeMatchCount', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='averageMatchWeight', full_name='edu.colorado.plv.fixr.protobuf.Iso.averageMatchWeight', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='averageDataNodeInDegree', full_name='edu.colorado.plv.fixr.protobuf.Iso.averageDataNodeInDegree', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='averageDataNodeOutDegree', full_name='edu.colorado.plv.fixr.protobuf.Iso.averageDataNodeOutDegree', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='averageMethodNodeInDegree', full_name='edu.colorado.plv.fixr.protobuf.Iso.averageMethodNodeInDegree', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='averageMethodNodeOutDegree', full_name='edu.colorado.plv.fixr.protobuf.Iso.averageMethodNodeOutDegree', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ISO_MAPNODE, _ISO_MAPEDGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=651,
)

_ISO_MAPNODE.containing_type = _ISO
_ISO_MAPEDGE.containing_type = _ISO
_ISO.fields_by_name['map_node'].message_type = _ISO_MAPNODE
_ISO.fields_by_name['map_edge'].message_type = _ISO_MAPEDGE
DESCRIPTOR.message_types_by_name['Iso'] = _ISO

Iso = _reflection.GeneratedProtocolMessageType('Iso', (_message.Message,), dict(

  MapNode = _reflection.GeneratedProtocolMessageType('MapNode', (_message.Message,), dict(
    DESCRIPTOR = _ISO_MAPNODE,
    __module__ = 'proto_iso_pb2'
    # @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Iso.MapNode)
    ))
  ,

  MapEdge = _reflection.GeneratedProtocolMessageType('MapEdge', (_message.Message,), dict(
    DESCRIPTOR = _ISO_MAPEDGE,
    __module__ = 'proto_iso_pb2'
    # @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Iso.MapEdge)
    ))
  ,
  DESCRIPTOR = _ISO,
  __module__ = 'proto_iso_pb2'
  # @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Iso)
  ))
_sym_db.RegisterMessage(Iso)
_sym_db.RegisterMessage(Iso.MapNode)
_sym_db.RegisterMessage(Iso.MapEdge)


# @@protoc_insertion_point(module_scope)
