ALL: cluster_1
	
cluster_1:
	time -p (ulimit -t 10; /Users/sergiomover/works/projects/muse/repos/FixrGraphIso/build/src/fixrgraphiso/frequentsubgraphs -f 2 -o /Users/sergiomover/works/projects/muse/repos/FixrGraph/python/fixrgraph/test/test_data/clusters_data/all_clusters/cluster_1/cluster_1_info.txt -m /Users/sergiomover/works/projects/muse/repos/FixrGraph/python/fixrgraph/test/test_data/clusters_data/all_clusters/cluster_1/methods_1.txt -p /Users/sergiomover/works/projects/muse/repos/FixrGraph/python/fixrgraph/test/test_data/clusters_data/all_clusters/cluster_1 /Users/sergiomover/works/projects/muse/repos/FixrGraph/python/fixrgraph/test/test_data/clusters_data/all_clusters/cluster_1/*.acdfg.bin > /Users/sergiomover/works/projects/muse/repos/FixrGraph/python/fixrgraph/test/test_data/clusters_data/all_clusters/cluster_1/run1.out 2> /Users/sergiomover/works/projects/muse/repos/FixrGraph/python/fixrgraph/test/test_data/clusters_data/all_clusters/cluster_1/run1.err.out)


